---
name: test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions: {}
    steps:
      - id: create_token
        uses: suzuki-shunsuke/tibdex-github-app-token@55429bbc082600559820fc71ef237b3f0e2a50a1 # v3.0.0
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - run: gh pr comment -R "$GITHUB_REPOSITORY" "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ steps.create_token.outputs.token }}
          NUMBER: ${{ github.event.pull_request.number }}
          BODY: hello
