---
name: test
on: pull_request
jobs:
  test-amd64:
    runs-on: macos-26-intel
    timeout-minutes: 15
    permissions: {}
    steps:
      - run: go version

  test-arm64:
    runs-on: macos-26
    timeout-minutes: 15
    permissions: {}
    steps:
      - run: go version
